--- !ditz.rubyforge.org,2008-03-06/project 
name: Ocean
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Ocean
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: cluster
- !ditz.rubyforge.org,2008-03-06/component 
  name: http-binding
- !ditz.rubyforge.org,2008-03-06/component 
  name: jingle
- !ditz.rubyforge.org,2008-03-06/component 
  name: tools
releases: []

